#!/system/bin/sh
#
# Load any extra modules

#MODULES="ipv6"

#for i in $MODULES;
#do
#    modprobe $i;
#done

# Workaround for rmmod
mount -o remount,rw /dev/block/mtdblock0 /system
KERNEL=`/system/xbin/uname -r`
DIRECTORY=/system/modules/$KERNEL
if [ ! -d "$DIRECTORY" ]; then
	mkdir -p /system/modules
	/system/xbin/ln -s /system/lib/modules/ $DIRECTORY
fi
